'''
Created on May 2, 2015
@author: Adam Biesenbach
'''

from UserInput.ValidateInput import Return311Choice  
from UserInput.ChooseAdditionalOutput import ValidateAddChartChoice
from Plotting.CreatePiePlots import CreateAllComplaintPiePlot
from Plotting.CreateBarCharts import CreateAgencyBarPlots, CreateBoroughBarPlots, CreateZIPBarPlots
from CreateIndividualComplaintCharts import CreateIndividualCharts
import pandas as pd
import sys 

def CreatePlots(RawDF):
    ''' This function takes the input for the agency/complaint type/date range 
    generated by the user, and creates the analysis charts. '''
    
    while True:
        ''' Prompt the user for a complaint type and a date range, and return these choices along 
        with the truncated data. '''
                
        (FirstDate, LastDate, ComplaintData, ComplaintChoice, Agency) = Return311Choice(RawDF)
                
        ''' Once the heatmaps are created, the user is prompted again for another choice. 
            If they want to break out the while loop and exit the program, they can do this at any time 
            by typing 'finish' at any of the prompts. '''
        
        
        # If the user typed 'finish', then break out of the loop and exit the program.
        if Agency =='finish':
            break
        
        # If the user type 'back', then they wanted to return to the Agency compaint menu.
        elif Agency =='back':
            continue
            
        # If the don't want to break out of the loop, we create the charts for this subset of data, and then prompt them again. 
        else:
            print '\n'
            print 'Creating heatmap, scatter plot and pie plot for complaint type: ' + str(ComplaintChoice) + ', and the date range: ' + str(pd.to_datetime(FirstDate).date()) + " through " + str(pd.to_datetime(LastDate).date())
       
            CreateIndividualCharts(ComplaintChoice, ComplaintData, FirstDate, LastDate)
        

        # The ChooseAdditionalOutput function prompts the user for their yes/no answer for more output. 
        Choice = ValidateAddChartChoice()

        if Choice == 'yes':
            
            RawDFDateReduced = RawDF[FirstDate:LastDate]

            ''' Create pie plots for subset of data.'''
                        
            CreateAllComplaintPiePlot(RawDFDateReduced, FirstDate, LastDate)
            
            ''' Create bar plots for subset of data.'''
            
            CreateAgencyBarPlots(RawDFDateReduced, FirstDate, LastDate)    
            CreateBoroughBarPlots(RawDFDateReduced, FirstDate, LastDate)     
            CreateZIPBarPlots(RawDFDateReduced, FirstDate, LastDate)
        
        elif Choice == 'finish':
            
            print "exiting program."
            print '\n'
            
            sys.exit(0)
            
        # This continue statement will allow us to prompt the user again for another 
        # choice of agency/complaint type/ date range. 
        
        continue  
